import { signIn, signOut, useSession } from "next-auth/client";
import { useRecoilState } from "recoil";
import { cartItems as initial, inCart as initialinCart } from "../store";
import CartItem from "../components/CartItem";


import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { imageUrl, twoDecimals, API_URL } from "../helpers";
import styles from "../styles/Home.module.css";

export default function Home({ products }) {
  console.log(products);
  const [session, loading] = useSession();
  const [cartItems, setCartItems] = useRecoilState(initial);
  // const [inCart, setinCart] = useRecoilState(initialinCart(product.id));

  const addToCart = (product) => {
    if (cartItems.some((i) => i.id === product.id)) {
      let newCart = cartItems.filter((i) => i.id !== product.id);
      setCartItems(newCart);
    } else {
      let newProduct = { ...product };
      newProduct.quantity = 1;
      setCartItems([newProduct, ...cartItems]);
    }
  };

  return (
    <div>
      <Head>
        <title>Next Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* signin logic */}
      {/* {!session && (
        <>
          Not signed in <br />
          <button onClick={() => signIn()}>Sign in</button>
        </>
      )}
      {session && (
        <>cartItems.includes(product) &&
          Signed in as {session.user.email} <br />
          <button onClick={() => signOut()}>Sign out</button>
        </>
      )} */}

      {products.map((product) => {
        return (
          <CartItem product={product} addToCart={addToCart} key={product.id} />
        );
      })}
    </div>
  );
}

export const getStaticProps = async () => {
  const products_resp = await fetch(`${API_URL}/products`);
  const products = await products_resp.json();

  return { props: { products } };
};
